In [2]:
import pandas as pd

In [3]:
data = {
    "title": ["The Shawshank Redemption", "The Godfather", "The Dark Knight", "Pulp Fiction", "Forrest Gump"],
    "rating": [9.3, 9.2, 9.0, 8.9, 8.8]
}
movies = pd.DataFrame(data)

movies

                      title  rating
0  The Shawshank Redemption     9.3
1             The Godfather     9.2
2           The Dark Knight     9.0
3              Pulp Fiction     8.9
4              Forrest Gump     8.8

In [4]:
movies.shape

(5, 2)

In [5]:
movies.columns

Index(['title', 'rating'], dtype='str')

In [6]:
movies["title"]

0    The Shawshank Redemption
1               The Godfather
2             The Dark Knight
3                Pulp Fiction
4                Forrest Gump
Name: title, dtype: str

In [7]:
movies["rating"]

0    9.3
1    9.2
2    9.0
3    8.9
4    8.8
Name: rating, dtype: float64

In [8]:
movies.head()

                      title  rating
0  The Shawshank Redemption     9.3
1             The Godfather     9.2
2           The Dark Knight     9.0
3              Pulp Fiction     8.9
4              Forrest Gump     8.8

In [9]:
import pandas as pd

movies = pd.read_csv("../data/tmdb_5000_movies.csv")
credits = pd.read_csv("../data/tmdb_5000_credits.csv")

In [10]:
print("Movies shape:", movies.shape)
print("Credits shape:", credits.shape)

Movies shape: (4803, 20)
Credits shape: (4803, 4)

In [11]:
print("Movies columns:")
print(movies.columns)

print("\nCredits columns:")
print(credits.columns)

Movies columns:
Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='str')

Credits columns:
Index(['movie_id', 'title', 'cast', 'crew'], dtype='str')

In [12]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [13]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [14]:
movies[["title", "genres", "keywords", "overview"]].head()

,title,genres,keywords,overview
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha..."
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca..."

In [15]:
credits[["title", "cast", "crew"]].head()

,title,cast,crew
0,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [16]:
movies[["title", "genres", "keywords", "overview"]].isnull().sum()

title       0
genres      0
keywords    0
overview    3
dtype: int64

In [17]:
credits[["title", "cast", "crew"]].isnull().sum()

title    0
cast     0
crew     0
dtype: int64

In [18]:
movies[["title", "genres", "keywords", "overview"]].dtypes

title       str
genres      str
keywords    str
overview    str
dtype: object

In [19]:
credits[["title", "cast", "crew"]].dtypes

title    str
cast     str
crew     str
dtype: object

In [20]:
type(movies.loc[0, "genres"])

str

In [21]:
print(movies.loc[0, "genres"])
print(type(movies.loc[0, "genres"]))

[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]
<class 'str'>

In [22]:
import ast

genres = ast.literal_eval(movies.loc[0, "genres"])

print(genres)
print(type(genres))

[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 878, 'name': 'Science Fiction'}]
<class 'list'>

In [23]:
for genre in genres:
    print(genre["name"])

Action
Adventure
Fantasy
Science Fiction

In [24]:
genre

{'id': 878, 'name': 'Science Fiction'}

In [25]:
genre["name"]

'Science Fiction'

In [26]:
def convert_genres(text):
    genre_list = ast.literal_eval(text)

    name = []
    for genre in genre_list:
        name.append(genre["name"])

    return " ".join(name)

In [27]:
convert_genres(movies.loc[0, "genres"])

'Action Adventure Fantasy Science Fiction'

In [28]:
movies["genres"] = movies["genres"].apply(convert_genres)

In [29]:
movies[["title", "genres"]].head()

,title,genres
0,Avatar,Action Adventure Fantasy Science Fiction
1,Pirates of the Caribbean: At World's End,Adventure Fantasy Action
2,Spectre,Action Adventure Crime
3,The Dark Knight Rises,Action Crime Drama Thriller
4,John Carter,Action Adventure Science Fiction

In [30]:
def convert_names(text):
    items = ast.literal_eval(text)

    names = []

    for item in items:
        names.append(item["name"])
    return " ".join(names)

In [31]:
movies["keywords"] = movies["keywords"].apply(convert_names)

In [32]:
movies[["title", "keywords"]].head()

,title,keywords
0,Avatar,culture clash future space war space colony so...
1,Pirates of the Caribbean: At World's End,ocean drug abuse exotic island east india trad...
2,Spectre,spy based on novel secret agent sequel mi6 bri...
3,The Dark Knight Rises,dc comics crime fighter terrorist secret ident...
4,John Carter,based on novel mars medallion space travel pri...

In [33]:
movies[["title", "genres", "keywords"]].head()

,title,genres,keywords
0,Avatar,Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...
1,Pirates of the Caribbean: At World's End,Adventure Fantasy Action,ocean drug abuse exotic island east india trad...
2,Spectre,Action Adventure Crime,spy based on novel secret agent sequel mi6 bri...
3,The Dark Knight Rises,Action Crime Drama Thriller,dc comics crime fighter terrorist secret ident...
4,John Carter,Action Adventure Science Fiction,based on novel mars medallion space travel pri...

In [34]:
def convert_cast(text):
    cast_list = ast.literal_eval(text)

    names = []

    for cast in cast_list[:3]:  # Limit to the first 3 cast members
        names.append(cast["name"])
    return " ".join(names)

In [35]:
movies["cast"] = credits["cast"].apply(convert_cast)

In [36]:
movies[["title", "cast"]].head()

,title,cast
0,Avatar,Sam Worthington Zoe Saldana Sigourney Weaver
1,Pirates of the Caribbean: At World's End,Johnny Depp Orlando Bloom Keira Knightley
2,Spectre,Daniel Craig Christoph Waltz Léa Seydoux
3,The Dark Knight Rises,Christian Bale Michael Caine Gary Oldman
4,John Carter,Taylor Kitsch Lynn Collins Samantha Morton

In [37]:
def get_director(text):
    crew_list = ast.literal_eval(text)

    for crew in crew_list:
        if crew["job"] == "Director":
            return crew["name"]
    return ""

In [38]:
movies["director"] = credits["crew"].apply(get_director)

In [39]:
movies[["title", "director"]].head()

                                      title           director
0                                    Avatar      James Cameron
1  Pirates of the Caribbean: At World's End     Gore Verbinski
2                                   Spectre         Sam Mendes
3                     The Dark Knight Rises  Christopher Nolan
4                               John Carter     Andrew Stanton

In [ ]:
movies[["id", "title", "genres", "keywords", "cast", "director"]].head()

,title,genres,keywords,cast,director
0,Avatar,Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...,Sam Worthington Zoe Saldana Sigourney Weaver,James Cameron
1,Pirates of the Caribbean: At World's End,Adventure Fantasy Action,ocean drug abuse exotic island east india trad...,Johnny Depp Orlando Bloom Keira Knightley,Gore Verbinski
2,Spectre,Action Adventure Crime,spy based on novel secret agent sequel mi6 bri...,Daniel Craig Christoph Waltz Léa Seydoux,Sam Mendes
3,The Dark Knight Rises,Action Crime Drama Thriller,dc comics crime fighter terrorist secret ident...,Christian Bale Michael Caine Gary Oldman,Christopher Nolan
4,John Carter,Action Adventure Science Fiction,based on novel mars medallion space travel pri...,Taylor Kitsch Lynn Collins Samantha Morton,Andrew Stanton

In [41]:
movies["overview"] = movies["overview"].fillna("")

In [42]:
movies["overview"].isnull().sum()

np.int64(0)

In [43]:
movies = movies[[ "title", "genres", "keywords", "overview", "cast", "director"]]

In [44]:
movies["tags"] = (
    movies["genres"] + " " + 
    movies["keywords"] + " " + 
    movies["overview"] + " " + 
    movies["cast"] + " " + 
    movies["director"]
)

In [45]:
movies[["title", "tags"]].head()

,title,tags
0,Avatar,Action Adventure Fantasy Science Fiction cultu...
1,Pirates of the Caribbean: At World's End,Adventure Fantasy Action ocean drug abuse exot...
2,Spectre,Action Adventure Crime spy based on novel secr...
3,The Dark Knight Rises,Action Crime Drama Thriller dc comics crime fi...
4,John Carter,Action Adventure Science Fiction based on nove...

In [46]:
movies["tags"] = movies["tags"].str.lower()

In [47]:
movies[["title", "tags"]].head()

,title,tags
0,Avatar,action adventure fantasy science fiction cultu...
1,Pirates of the Caribbean: At World's End,adventure fantasy action ocean drug abuse exot...
2,Spectre,action adventure crime spy based on novel secr...
3,The Dark Knight Rises,action crime drama thriller dc comics crime fi...
4,John Carter,action adventure science fiction based on nove...

In [48]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [49]:
vectorizer = TfidfVectorizer(max_features=5000)

In [50]:
vectors = vectorizer.fit_transform(movies["tags"])

In [51]:
print(vectors.shape)

(4803, 5000)

In [52]:
vectorizer.get_feature_names_out()[:20]

array(['000', '007', '10', '100', '11', '12', '13', '14', '15', '16',
       '17', '17th', '18', '18th', '19', '1930s', '1940s', '1950s',
       '1960s', '1970s'], dtype=object)

In [53]:
print(type(vectors))

<class 'scipy.sparse._csr.csr_matrix'>

In [54]:
from sklearn.metrics.pairwise import cosine_similarity

In [55]:
similarity = cosine_similarity(vectors)

In [56]:
print(similarity.shape)

(4803, 4803)

In [57]:
similarity[0]

array([1.        , 0.0370775 , 0.03319446, ..., 0.03121119, 0.04577036,
       0.00799478], shape=(4803,))

In [58]:
list(enumerate(similarity[0][:10]))

[(0, np.float64(1.0000000000000002)),
 (1, np.float64(0.03707749519433735)),
 (2, np.float64(0.03319446092699622)),
 (3, np.float64(0.0266833316193343)),
 (4, np.float64(0.2323784443092509)),
 (5, np.float64(0.08342565091841642)),
 (6, np.float64(0.025765475708114507)),
 (7, np.float64(0.09706524643115665)),
 (8, np.float64(0.023551947366982403)),
 (9, np.float64(0.03465972982352925))]

In [59]:
sorted(list(enumerate(similarity[0])), key=lambda x: x[1], reverse=True)[:10]

[(0, np.float64(1.0000000000000002)),
 (2403, np.float64(0.40502151583543555)),
 (3158, np.float64(0.3536204624068246)),
 (1531, np.float64(0.34480010913442444)),
 (838, np.float64(0.3365465699682493)),
 (1914, np.float64(0.3202185751905406)),
 (2015, np.float64(0.30351143804230457)),
 (4332, np.float64(0.29145997970028104)),
 (373, np.float64(0.2795977577661536)),
 (461, np.float64(0.27784918378509005))]

In [60]:
movies.iloc[2403]["title"]

'Aliens'

In [61]:
movies.iloc[3158]["title"]

'Alien'

In [62]:
movies.iloc[1531]["title"]

'Moonraker'

In [63]:
for movie in sorted(list(enumerate(similarity[0])), 
                    key=lambda x: x[1], 
                    reverse=True)[1:6]:
    
    print(movies.iloc[movie[0]]["title"], "→", movie[1])

Aliens → 0.40502151583543555
Alien → 0.3536204624068246
Moonraker → 0.34480010913442444
Alien³ → 0.3365465699682493
Lifeforce → 0.3202185751905406

In [64]:
movie_indices = pd.Series(movies.index, index=movies["title"]).drop_duplicates()

In [65]:
movie_indices["Avatar"]

np.int64(0)

In [77]:
def recommend(movie):
    movie = movie.lower()

    title_map = {
        title.lower(): title
        for title in movies["title"]
    }

    if movie not in title_map:
        print("Movie not found in the dataset.")
        return []

    actual_title = title_map[movie]
    index = movie_indices[actual_title]

    similar_movies = sorted(
        list(enumerate(similarity[index])),
        key=lambda x: x[1],
        reverse=True
    )

    recommendations = []

    for i in similar_movies[1:6]:
        recommendations.append({
            "title": movies.iloc[i[0]]["title"],
            "score": float(round(i[1], 3))
        })

    return recommendations

In [67]:
recommend("Avatar")

Recommendations for: Avatar

Aliens → 0.405
Alien → 0.354
Moonraker → 0.345
Alien³ → 0.337
Lifeforce → 0.32

In [68]:
recommend("The Dark Knight Rises")

Recommendations for: The Dark Knight Rises

The Dark Knight → 0.508
Batman Begins → 0.438
Batman Returns → 0.422
Batman → 0.395
Batman Forever → 0.371

In [69]:
recommend("Avengers 999")

Movie not found in the dataset.

In [70]:
recommend("The Dark Knight Rises")

Recommendations for: The Dark Knight Rises

The Dark Knight → 0.508
Batman Begins → 0.438
Batman Returns → 0.422
Batman → 0.395
Batman Forever → 0.371

In [71]:
recommend("Titanic")

Recommendations for: Titanic

Romance & Cigarettes → 0.227
In the Heart of the Sea → 0.225
Captain Phillips → 0.223
Poseidon → 0.216
Ghost Ship → 0.215

In [72]:
movies["title"].duplicated().sum()

np.int64(3)

In [74]:
recommend("Avatar")

[{'title': 'Aliens', 'score': np.float64(0.405)},
 {'title': 'Alien', 'score': np.float64(0.354)},
 {'title': 'Moonraker', 'score': np.float64(0.345)},
 {'title': 'Alien³', 'score': np.float64(0.337)},
 {'title': 'Lifeforce', 'score': np.float64(0.32)}]

In [75]:
movies["title"].duplicated().sum()

np.int64(3)

In [76]:
movies[movies["title"].duplicated(keep=False)].sort_values("title")[["title"]]

                title
1359           Batman
4267           Batman
3647  Out of the Blue
3693  Out of the Blue
972          The Host
2877         The Host

In [79]:
recommend("AVATAR")

[{'title': 'Aliens', 'score': 0.405},
 {'title': 'Alien', 'score': 0.354},
 {'title': 'Moonraker', 'score': 0.345},
 {'title': 'Alien³', 'score': 0.337},
 {'title': 'Lifeforce', 'score': 0.32}]

In [80]:
recommend("Avatar")

[{'title': 'Aliens', 'score': 0.405},
 {'title': 'Alien', 'score': 0.354},
 {'title': 'Moonraker', 'score': 0.345},
 {'title': 'Alien³', 'score': 0.337},
 {'title': 'Lifeforce', 'score': 0.32}]

In [82]:
import sys
sys.path.append("..")

In [83]:
from src.recommender import hello

print(hello())

Recommendation system is working!

In [1]:
import sys
sys.path.append("..")

In [3]:
from src.recommender import recommend

In [4]:
recommend("Avatar")

[{'title': 'Aliens', 'score': 0.405},
 {'title': 'Alien', 'score': 0.354},
 {'title': 'Moonraker', 'score': 0.345},
 {'title': 'Alien³', 'score': 0.337},
 {'title': 'Lifeforce', 'score': 0.32}]

In [2]:
import sys
sys.path.append("..")

In [3]:
from src.recommender import recommend

recommend("Avatar")

[{'id': 679, 'title': 'Aliens', 'score': 0.405},
 {'id': 348, 'title': 'Alien', 'score': 0.354},
 {'id': 698, 'title': 'Moonraker', 'score': 0.345},
 {'id': 8077, 'title': 'Alien³', 'score': 0.337},
 {'id': 11954, 'title': 'Lifeforce', 'score': 0.32}]